-- ============================================================
-- Custom Object Tables (auto-generated by scripts/generate_schema.py)
-- Do not edit manually — re-run the script to regenerate.
-- ============================================================

-- ── About Me (AboutMe__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS aboutme (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    ownerid                        VARCHAR(18) NOT NULL,  -- SF: OwnerId (reference)
    name                           VARCHAR(80),  -- SF: Name (string)
    content                        TEXT,  -- SF: Content__c (textarea)
    entry_date                     DATE,  -- SF: Entry_Date__c (date)
    category                       VARCHAR(255),  -- SF: Category__c (picklist)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_aboutme_sf_id ON aboutme(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_aboutme_sync  ON aboutme(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_aboutme_ownerid ON aboutme(ownerid);

-- ── Account (Account) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS account (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    name                           VARCHAR(255) NOT NULL,  -- SF: Name (string)
    type                           VARCHAR(255),  -- SF: Type (picklist)
    parentid                       VARCHAR(18),  -- SF: ParentId (reference)
    billingstreet                  TEXT,  -- SF: BillingStreet (textarea)
    billingcity                    VARCHAR(40),  -- SF: BillingCity (string)
    billingstate                   VARCHAR(80),  -- SF: BillingState (string)
    billingpostalcode              VARCHAR(20),  -- SF: BillingPostalCode (string)
    billingcountry                 VARCHAR(80),  -- SF: BillingCountry (string)
    billingstatecode               VARCHAR(10),  -- SF: BillingStateCode (picklist)
    billingcountrycode             VARCHAR(10),  -- SF: BillingCountryCode (picklist)
    billinglatitude                NUMERIC(18,6),  -- SF: BillingLatitude (double)
    billinglongitude               NUMERIC(18,6),  -- SF: BillingLongitude (double)
    billinggeocodeaccuracy         VARCHAR(40),  -- SF: BillingGeocodeAccuracy (picklist)
    shippingstreet                 TEXT,  -- SF: ShippingStreet (textarea)
    shippingcity                   VARCHAR(40),  -- SF: ShippingCity (string)
    shippingstate                  VARCHAR(80),  -- SF: ShippingState (string)
    shippingpostalcode             VARCHAR(20),  -- SF: ShippingPostalCode (string)
    shippingcountry                VARCHAR(80),  -- SF: ShippingCountry (string)
    shippingstatecode              VARCHAR(10),  -- SF: ShippingStateCode (picklist)
    shippingcountrycode            VARCHAR(10),  -- SF: ShippingCountryCode (picklist)
    shippinglatitude               NUMERIC(18,6),  -- SF: ShippingLatitude (double)
    shippinglongitude              NUMERIC(18,6),  -- SF: ShippingLongitude (double)
    shippinggeocodeaccuracy        VARCHAR(40),  -- SF: ShippingGeocodeAccuracy (picklist)
    phone                          VARCHAR(40),  -- SF: Phone (phone)
    fax                            VARCHAR(40),  -- SF: Fax (phone)
    accountnumber                  VARCHAR(40),  -- SF: AccountNumber (string)
    website                        VARCHAR(1024),  -- SF: Website (url)
    sic                            VARCHAR(20),  -- SF: Sic (string)
    industry                       VARCHAR(255),  -- SF: Industry (picklist)
    annualrevenue                  NUMERIC(18,2),  -- SF: AnnualRevenue (currency)
    numberofemployees              INTEGER,  -- SF: NumberOfEmployees (int)
    ownership                      VARCHAR(255),  -- SF: Ownership (picklist)
    tickersymbol                   VARCHAR(20),  -- SF: TickerSymbol (string)
    description                    TEXT,  -- SF: Description (textarea)
    rating                         VARCHAR(255),  -- SF: Rating (picklist)
    site                           VARCHAR(80),  -- SF: Site (string)
    ownerid                        VARCHAR(18) NOT NULL,  -- SF: OwnerId (reference)
    ispartner                      BOOLEAN NOT NULL,  -- SF: IsPartner (boolean)
    iscustomerportal               BOOLEAN NOT NULL,  -- SF: IsCustomerPortal (boolean)
    jigsaw                         VARCHAR(20),  -- SF: Jigsaw (string)
    cleanstatus                    VARCHAR(40),  -- SF: CleanStatus (picklist)
    accountsource                  VARCHAR(255),  -- SF: AccountSource (picklist)
    dunsnumber                     VARCHAR(9),  -- SF: DunsNumber (string)
    tradestyle                     VARCHAR(255),  -- SF: Tradestyle (string)
    naicscode                      VARCHAR(8),  -- SF: NaicsCode (string)
    naicsdesc                      VARCHAR(120),  -- SF: NaicsDesc (string)
    yearstarted                    VARCHAR(4),  -- SF: YearStarted (string)
    sicdesc                        VARCHAR(80),  -- SF: SicDesc (string)
    dandbcompanyid                 VARCHAR(18),  -- SF: DandbCompanyId (reference)
    operatinghoursid               VARCHAR(18),  -- SF: OperatingHoursId (reference)
    customerpriority               VARCHAR(255),  -- SF: CustomerPriority__c (picklist)
    sla                            VARCHAR(255),  -- SF: SLA__c (picklist)
    active                         VARCHAR(255),  -- SF: Active__c (picklist)
    numberoflocations              NUMERIC(18,6),  -- SF: NumberofLocations__c (double)
    upsellopportunity              VARCHAR(255),  -- SF: UpsellOpportunity__c (picklist)
    slaserialnumber                VARCHAR(10),  -- SF: SLASerialNumber__c (string)
    slaexpirationdate              DATE,  -- SF: SLAExpirationDate__c (date)
    job                            BOOLEAN NOT NULL,  -- SF: Job__c (boolean)
    company_research               TEXT,  -- SF: Company_Research__c (textarea)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_account_sf_id ON account(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_account_sync  ON account(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_account_parentid ON account(parentid);
CREATE INDEX        IF NOT EXISTS idx_account_ownerid ON account(ownerid);
CREATE INDEX        IF NOT EXISTS idx_account_dandbcompanyid ON account(dandbcompanyid);
CREATE INDEX        IF NOT EXISTS idx_account_operatinghoursid ON account(operatinghoursid);

-- ── Anthropic Settings (AnthropicSettings__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS anthropicsettings (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    name                           VARCHAR(80),  -- SF: Name (string)
    setupownerid                   VARCHAR(18),  -- SF: SetupOwnerId (reference)
    api_key                        VARCHAR(255),  -- SF: API_Key__c (string)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_anthropicsettings_sf_id ON anthropicsettings(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_anthropicsettings_sync  ON anthropicsettings(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_anthropicsettings_setupownerid ON anthropicsettings(setupownerid);

-- ── Award (Award__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS award (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    ownerid                        VARCHAR(18) NOT NULL,  -- SF: OwnerId (reference)
    name                           VARCHAR(80),  -- SF: Name (string)
    credential_id                  VARCHAR(255),  -- SF: Credential_ID__c (string)
    credential_url                 VARCHAR(1024),  -- SF: Credential_URL__c (url)
    date_earned                    DATE,  -- SF: Date_Earned__c (date)
    description                    TEXT,  -- SF: Description__c (textarea)
    expiration_date                DATE,  -- SF: Expiration_Date__c (date)
    issuing_organization           VARCHAR(255),  -- SF: Issuing_Organization__c (string)
    type                           VARCHAR(255),  -- SF: Type__c (picklist)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_award_sf_id ON award(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_award_sync  ON award(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_award_ownerid ON award(ownerid);

-- ── Contact (Contact) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS contact (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    accountid                      VARCHAR(18),  -- SF: AccountId (reference)
    lastname                       VARCHAR(80) NOT NULL,  -- SF: LastName (string)
    firstname                      VARCHAR(40),  -- SF: FirstName (string)
    salutation                     VARCHAR(40),  -- SF: Salutation (picklist)
    otherstreet                    TEXT,  -- SF: OtherStreet (textarea)
    othercity                      VARCHAR(40),  -- SF: OtherCity (string)
    otherstate                     VARCHAR(80),  -- SF: OtherState (string)
    otherpostalcode                VARCHAR(20),  -- SF: OtherPostalCode (string)
    othercountry                   VARCHAR(80),  -- SF: OtherCountry (string)
    otherstatecode                 VARCHAR(10),  -- SF: OtherStateCode (picklist)
    othercountrycode               VARCHAR(10),  -- SF: OtherCountryCode (picklist)
    otherlatitude                  NUMERIC(18,6),  -- SF: OtherLatitude (double)
    otherlongitude                 NUMERIC(18,6),  -- SF: OtherLongitude (double)
    othergeocodeaccuracy           VARCHAR(40),  -- SF: OtherGeocodeAccuracy (picklist)
    mailingstreet                  TEXT,  -- SF: MailingStreet (textarea)
    mailingcity                    VARCHAR(40),  -- SF: MailingCity (string)
    mailingstate                   VARCHAR(80),  -- SF: MailingState (string)
    mailingpostalcode              VARCHAR(20),  -- SF: MailingPostalCode (string)
    mailingcountry                 VARCHAR(80),  -- SF: MailingCountry (string)
    mailingstatecode               VARCHAR(10),  -- SF: MailingStateCode (picklist)
    mailingcountrycode             VARCHAR(10),  -- SF: MailingCountryCode (picklist)
    mailinglatitude                NUMERIC(18,6),  -- SF: MailingLatitude (double)
    mailinglongitude               NUMERIC(18,6),  -- SF: MailingLongitude (double)
    mailinggeocodeaccuracy         VARCHAR(40),  -- SF: MailingGeocodeAccuracy (picklist)
    phone                          VARCHAR(40),  -- SF: Phone (phone)
    fax                            VARCHAR(40),  -- SF: Fax (phone)
    mobilephone                    VARCHAR(40),  -- SF: MobilePhone (phone)
    homephone                      VARCHAR(40),  -- SF: HomePhone (phone)
    otherphone                     VARCHAR(40),  -- SF: OtherPhone (phone)
    assistantphone                 VARCHAR(40),  -- SF: AssistantPhone (phone)
    reportstoid                    VARCHAR(18),  -- SF: ReportsToId (reference)
    email                          VARCHAR(80),  -- SF: Email (email)
    title                          VARCHAR(128),  -- SF: Title (string)
    department                     VARCHAR(80),  -- SF: Department (string)
    assistantname                  VARCHAR(40),  -- SF: AssistantName (string)
    leadsource                     VARCHAR(255),  -- SF: LeadSource (picklist)
    birthdate                      DATE,  -- SF: Birthdate (date)
    description                    TEXT,  -- SF: Description (textarea)
    ownerid                        VARCHAR(18) NOT NULL,  -- SF: OwnerId (reference)
    emailbouncedreason             VARCHAR(255),  -- SF: EmailBouncedReason (string)
    emailbounceddate               TIMESTAMP WITH TIME ZONE,  -- SF: EmailBouncedDate (datetime)
    jigsaw                         VARCHAR(20),  -- SF: Jigsaw (string)
    cleanstatus                    VARCHAR(40),  -- SF: CleanStatus (picklist)
    individualid                   VARCHAR(18),  -- SF: IndividualId (reference)
    contactsource                  VARCHAR(40),  -- SF: ContactSource (picklist)
    level                          VARCHAR(255),  -- SF: Level__c (picklist)
    languages                      VARCHAR(100),  -- SF: Languages__c (string)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_contact_sf_id ON contact(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_contact_sync  ON contact(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_contact_accountid ON contact(accountid);
CREATE INDEX        IF NOT EXISTS idx_contact_reportstoid ON contact(reportstoid);
CREATE INDEX        IF NOT EXISTS idx_contact_ownerid ON contact(ownerid);
CREATE INDEX        IF NOT EXISTS idx_contact_individualid ON contact(individualid);

-- ── Cover Letter (CoverLetter__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS coverletter (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    ownerid                        VARCHAR(18) NOT NULL,  -- SF: OwnerId (reference)
    name                           VARCHAR(80),  -- SF: Name (string)
    about_me_section               TEXT,  -- SF: About_Me_Section__c (textarea)
    address                        VARCHAR(255),  -- SF: Address__c (string)
    closing                        VARCHAR(255),  -- SF: Closing__c (string)
    company_research               TEXT,  -- SF: Company_Research__c (textarea)
    email                          VARCHAR(255),  -- SF: Email__c (string)
    first_name                     VARCHAR(255),  -- SF: First_Name__c (string)
    github_url                     VARCHAR(255),  -- SF: GitHub_URL__c (string)
    greeting                       VARCHAR(255),  -- SF: Greeting__c (string)
    job_description                TEXT,  -- SF: Job_Description__c (textarea)
    last_name                      VARCHAR(255),  -- SF: Last_Name__c (string)
    linkedin_url                   VARCHAR(255),  -- SF: LinkedIn_URL__c (string)
    middle_name                    VARCHAR(255),  -- SF: Middle_Name__c (string)
    notes                          TEXT,  -- SF: Notes__c (textarea)
    phone                          VARCHAR(255),  -- SF: Phone__c (string)
    photo                          VARCHAR(255),  -- SF: Photo__c (string)
    portfolio_url                  VARCHAR(255),  -- SF: Portfolio_URL__c (string)
    professional_title             VARCHAR(255),  -- SF: Professional_Title__c (string)
    resume                         VARCHAR(18),  -- SF: Resume__c (reference)
    status                         VARCHAR(255),  -- SF: Status__c (picklist)
    target_company                 VARCHAR(255),  -- SF: Target_Company__c (string)
    target_job_title               VARCHAR(255),  -- SF: Target_Job_Title__c (string)
    trailblazer_url                VARCHAR(255),  -- SF: Trailblazer_URL__c (string)
    why_company_section            TEXT,  -- SF: Why_Company_Section__c (textarea)
    why_me_section                 TEXT,  -- SF: Why_Me_Section__c (textarea)
    jobapplication                 VARCHAR(18),  -- SF: JobApplication__c (reference)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_coverletter_sf_id ON coverletter(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_coverletter_sync  ON coverletter(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_coverletter_ownerid ON coverletter(ownerid);
CREATE INDEX        IF NOT EXISTS idx_coverletter_resume ON coverletter(resume);
CREATE INDEX        IF NOT EXISTS idx_coverletter_jobapplication ON coverletter(jobapplication);

-- ── Education (Education__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS education (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    ownerid                        VARCHAR(18) NOT NULL,  -- SF: OwnerId (reference)
    name                           VARCHAR(80),  -- SF: Name (string)
    degree                         VARCHAR(255),  -- SF: Degree__c (string)
    graduation_year                VARCHAR(50),  -- SF: Graduation_Year__c (string)
    location                       VARCHAR(255),  -- SF: Location__c (string)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_education_sf_id ON education(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_education_sync  ON education(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_education_ownerid ON education(ownerid);

-- ── Experience (Experience__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS experience (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    name                           VARCHAR(80),  -- SF: Name (string)
    recordtypeid                   VARCHAR(18),  -- SF: RecordTypeId (reference)
    location__street__s            TEXT,  -- SF: Location__Street__s (textarea)
    location__city__s              VARCHAR(40),  -- SF: Location__City__s (string)
    location__postalcode__s        VARCHAR(20),  -- SF: Location__PostalCode__s (string)
    location__statecode__s         VARCHAR(10),  -- SF: Location__StateCode__s (picklist)
    location__countrycode__s       VARCHAR(10),  -- SF: Location__CountryCode__s (picklist)
    location__latitude__s          NUMERIC(18,6),  -- SF: Location__Latitude__s (double)
    location__longitude__s         NUMERIC(18,6),  -- SF: Location__Longitude__s (double)
    location__geocodeaccuracy__s   VARCHAR(40),  -- SF: Location__GeocodeAccuracy__s (picklist)
    start_date                     DATE NOT NULL,  -- SF: Start_Date__c (date)
    end_date                       DATE,  -- SF: End_Date__c (date)
    description                    TEXT,  -- SF: Description__c (textarea)
    skills                         TEXT NOT NULL,  -- SF: Skills__c (multipicklist)
    job                            VARCHAR(18) NOT NULL,  -- SF: Job__c (reference)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_experience_sf_id ON experience(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_experience_sync  ON experience(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_experience_recordtypeid ON experience(recordtypeid);
CREATE INDEX        IF NOT EXISTS idx_experience_job ON experience(job);

-- ── Job Application (JobApplication__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS jobapplication (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    ownerid                        VARCHAR(18) NOT NULL,  -- SF: OwnerId (reference)
    name                           VARCHAR(80),  -- SF: Name (string)
    account                        VARCHAR(18),  -- SF: Account__c (reference)
    company_research               TEXT,  -- SF: Company_Research__c (textarea)
    employment_type                VARCHAR(255),  -- SF: Employment_Type__c (picklist)
    job_description                TEXT,  -- SF: Job_Description__c (textarea)
    job_posting_url                VARCHAR(1024),  -- SF: Job_Posting_URL__c (url)
    job_title                      VARCHAR(255),  -- SF: Job_Title__c (string)
    recruiter                      VARCHAR(18),  -- SF: Recruiter__c (reference)
    status                         VARCHAR(255),  -- SF: Status__c (picklist)
    work_classification            VARCHAR(255),  -- SF: Work_Classification__c (picklist)
    annual_salary                  NUMERIC(18,2),  -- SF: Annual_Salary__c (currency)
    hourly_rate                    NUMERIC(18,2),  -- SF: Hourly_Rate__c (currency)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_jobapplication_sf_id ON jobapplication(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_jobapplication_sync  ON jobapplication(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_jobapplication_ownerid ON jobapplication(ownerid);
CREATE INDEX        IF NOT EXISTS idx_jobapplication_account ON jobapplication(account);
CREATE INDEX        IF NOT EXISTS idx_jobapplication_recruiter ON jobapplication(recruiter);

-- ── Job (Job__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS job (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    name                           VARCHAR(80),  -- SF: Name (string)
    start_date                     DATE NOT NULL,  -- SF: Start_Date__c (date)
    end_date                       DATE,  -- SF: End_Date__c (date)
    remote_work                    BOOLEAN NOT NULL,  -- SF: Remote_Work__c (boolean)
    job_location__street__s        TEXT,  -- SF: Job_Location__Street__s (textarea)
    job_location__city__s          VARCHAR(40),  -- SF: Job_Location__City__s (string)
    job_location__postalcode__s    VARCHAR(20),  -- SF: Job_Location__PostalCode__s (string)
    job_location__statecode__s     VARCHAR(10),  -- SF: Job_Location__StateCode__s (picklist)
    job_location__countrycode__s   VARCHAR(10),  -- SF: Job_Location__CountryCode__s (picklist)
    job_location__latitude__s      NUMERIC(18,6),  -- SF: Job_Location__Latitude__s (double)
    job_location__longitude__s     NUMERIC(18,6),  -- SF: Job_Location__Longitude__s (double)
    job_location__geocodeaccuracy__s VARCHAR(40),  -- SF: Job_Location__GeocodeAccuracy__s (picklist)
    company                        VARCHAR(18) NOT NULL,  -- SF: Company__c (reference)
    description                    TEXT,  -- SF: Description__c (textarea)
    icon                           VARCHAR(255),  -- SF: Icon__c (string)
    skills                         TEXT,  -- SF: Skills__c (multipicklist)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_job_sf_id ON job(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_job_sync  ON job(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_job_company ON job(company);

-- ── Resume Award (Resume_Award__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS resume_award (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    resume                         VARCHAR(18) NOT NULL,  -- SF: Resume__c (reference)
    award                          VARCHAR(18) NOT NULL,  -- SF: Award__c (reference)
    sort_order                     NUMERIC(18,6),  -- SF: Sort_Order__c (double)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_resume_award_sf_id ON resume_award(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_resume_award_sync  ON resume_award(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_resume_award_resume ON resume_award(resume);
CREATE INDEX        IF NOT EXISTS idx_resume_award_award ON resume_award(award);

-- ── Resume Education (Resume_Education__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS resume_education (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    resume                         VARCHAR(18) NOT NULL,  -- SF: Resume__c (reference)
    education                      VARCHAR(18) NOT NULL,  -- SF: Education__c (reference)
    sort_order                     NUMERIC(18,6),  -- SF: Sort_Order__c (double)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_resume_education_sf_id ON resume_education(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_resume_education_sync  ON resume_education(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_resume_education_resume ON resume_education(resume);
CREATE INDEX        IF NOT EXISTS idx_resume_education_education ON resume_education(education);

-- ── Resume Experience (Resume_Experience__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS resume_experience (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    resume                         VARCHAR(18) NOT NULL,  -- SF: Resume__c (reference)
    experience                     VARCHAR(18) NOT NULL,  -- SF: Experience__c (reference)
    sort_order                     NUMERIC(18,6),  -- SF: Sort_Order__c (double)
    tailored_description           TEXT,  -- SF: Tailored_Description__c (textarea)
    tailored_title                 VARCHAR(255),  -- SF: Tailored_Title__c (string)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_resume_experience_sf_id ON resume_experience(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_resume_experience_sync  ON resume_experience(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_resume_experience_resume ON resume_experience(resume);
CREATE INDEX        IF NOT EXISTS idx_resume_experience_experience ON resume_experience(experience);

-- ── Resume Strength (Resume_Strength__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS resume_strength (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    resume                         VARCHAR(18) NOT NULL,  -- SF: Resume__c (reference)
    strength                       VARCHAR(18) NOT NULL,  -- SF: Strength__c (reference)
    sort_order                     NUMERIC(18,6),  -- SF: Sort_Order__c (double)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_resume_strength_sf_id ON resume_strength(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_resume_strength_sync  ON resume_strength(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_resume_strength_resume ON resume_strength(resume);
CREATE INDEX        IF NOT EXISTS idx_resume_strength_strength ON resume_strength(strength);

-- ── Resume (Resume__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS resume (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    ownerid                        VARCHAR(18) NOT NULL,  -- SF: OwnerId (reference)
    name                           VARCHAR(80),  -- SF: Name (string)
    address                        VARCHAR(255),  -- SF: Address__c (string)
    display_name                   VARCHAR(255),  -- SF: Display_Name__c (string)
    email                          VARCHAR(80),  -- SF: Email__c (email)
    github_url                     VARCHAR(1024),  -- SF: GitHub_URL__c (url)
    job_description                TEXT,  -- SF: Job_Description__c (textarea)
    linkedin_url                   VARCHAR(1024),  -- SF: LinkedIn_URL__c (url)
    notes                          TEXT,  -- SF: Notes__c (textarea)
    phone                          VARCHAR(40),  -- SF: Phone__c (phone)
    portfolio_url                  VARCHAR(1024),  -- SF: Portfolio_URL__c (url)
    professional_title             VARCHAR(255),  -- SF: Professional_Title__c (string)
    quote                          TEXT,  -- SF: Quote__c (textarea)
    status                         VARCHAR(255),  -- SF: Status__c (picklist)
    summary                        TEXT,  -- SF: Summary__c (textarea)
    tagline                        VARCHAR(255),  -- SF: Tagline__c (string)
    target_company                 VARCHAR(255),  -- SF: Target_Company__c (string)
    target_job_title               VARCHAR(255),  -- SF: Target_Job_Title__c (string)
    template                       VARCHAR(255),  -- SF: Template__c (picklist)
    trailblazer_url                VARCHAR(1024),  -- SF: Trailblazer_URL__c (url)
    first_name                     VARCHAR(100),  -- SF: First_Name__c (string)
    last_name                      VARCHAR(100),  -- SF: Last_Name__c (string)
    middle_name                    VARCHAR(100),  -- SF: Middle_Name__c (string)
    show_experience_descriptions   BOOLEAN NOT NULL,  -- SF: Show_Experience_Descriptions__c (boolean)
    show_job_descriptions          BOOLEAN NOT NULL,  -- SF: Show_Job_Descriptions__c (boolean)
    show_project_descriptions      BOOLEAN NOT NULL,  -- SF: Show_Project_Descriptions__c (boolean)
    jobapplication                 VARCHAR(18),  -- SF: JobApplication__c (reference)
    overwrite_chronological_order  BOOLEAN NOT NULL,  -- SF: Overwrite_Chronological_Order__c (boolean)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_resume_sf_id ON resume(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_resume_sync  ON resume(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_resume_ownerid ON resume(ownerid);
CREATE INDEX        IF NOT EXISTS idx_resume_jobapplication ON resume(jobapplication);

-- ── Strength (Strength__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS strength (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    ownerid                        VARCHAR(18) NOT NULL,  -- SF: OwnerId (reference)
    name                           VARCHAR(80),  -- SF: Name (string)
    description                    TEXT,  -- SF: Description__c (textarea)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_strength_sf_id ON strength(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_strength_sync  ON strength(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_strength_ownerid ON strength(ownerid);

-- ── Interview (Interview__c) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS interview (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    ownerid                        VARCHAR(18),         -- SF: OwnerId (reference)
    name                           VARCHAR(80),         -- SF: Name (string)
    interview_date                 TIMESTAMP WITH TIME ZONE,  -- SF: Interview_Date__c (datetime)
    status                         VARCHAR(255),        -- SF: Status__c (picklist)
    type                           VARCHAR(255),        -- SF: Type__c (picklist)
    round                          VARCHAR(255),        -- SF: Round__c (string/picklist)
    outcome                        VARCHAR(255),        -- SF: Outcome__c (picklist)
    notes                          TEXT,                -- SF: Notes__c (textarea)
    jobapplication                 VARCHAR(18),         -- SF: JobApplication__c (reference)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_interview_sf_id ON interview(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_interview_sync  ON interview(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_interview_ownerid ON interview(ownerid);
CREATE INDEX        IF NOT EXISTS idx_interview_jobapplication ON interview(jobapplication);

-- ── Interview Contact (InterviewContact__c) ────────────────────────────
CREATE TABLE IF NOT EXISTS interviewcontact (
    id              BIGSERIAL PRIMARY KEY,
    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,
    ownerid                        VARCHAR(18),         -- SF: OwnerId (reference)
    name                           VARCHAR(80),         -- SF: Name (string)
    interview                      VARCHAR(18),         -- SF: Interview__c (reference)
    contact                        VARCHAR(18),         -- SF: Contact__c (reference)
    role                           VARCHAR(255),        -- SF: Role__c (picklist/string)
    notes                          TEXT,                -- SF: Notes__c (textarea)
    isdeleted          BOOLEAN,
    createddate        TIMESTAMP WITH TIME ZONE,
    createdbyid        VARCHAR(18),
    lastmodifieddate   TIMESTAMP WITH TIME ZONE,
    lastmodifiedbyid   VARCHAR(18),
    systemmodstamp     TIMESTAMP WITH TIME ZONE,
    lastvieweddate     TIMESTAMP WITH TIME ZONE,
    lastreferenceddate TIMESTAMP WITH TIME ZONE,
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_interviewcontact_sf_id      ON interviewcontact(salesforce_id);
CREATE INDEX        IF NOT EXISTS idx_interviewcontact_sync        ON interviewcontact(sync_status, last_synced);
CREATE INDEX        IF NOT EXISTS idx_interviewcontact_ownerid     ON interviewcontact(ownerid);
CREATE INDEX        IF NOT EXISTS idx_interviewcontact_interview   ON interviewcontact(interview);
CREATE INDEX        IF NOT EXISTS idx_interviewcontact_contact     ON interviewcontact(contact);
