"""
generate_schema.py

Reads Salesforce object metadata JSON files produced by:
  sf sobject describe --sobject <ObjectName> --json > metadata/<ObjectName>.json

Generates 02_custom_schema.sql with CREATE TABLE statements for each custom object.

Usage:
  python scripts/generate_schema.py

Expects metadata JSON files in: Salesforce_Projects/metadata/
Writes output to:               Docker_Projects/Salesforce_Backup/init/02_custom_schema.sql
"""

import json
import os
import glob
from pathlib import Path

# Paths
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
METADATA_DIR = Path("/home/wroachbarrette/Salesforce_Projects/metadata")
OUTPUT_FILE = PROJECT_ROOT / "init" / "02_custom_schema.sql"

# Salesforce type → PostgreSQL type mapping
SF_TYPE_MAP = {
    "id":               "VARCHAR(18)",
    "string":           "VARCHAR(255)",
    "textarea":         "TEXT",
    "longtextarea":     "TEXT",
    "richtextarea":     "TEXT",
    "boolean":          "BOOLEAN",
    "int":              "INTEGER",
    "double":           "NUMERIC(18,6)",
    "currency":         "NUMERIC(18,2)",
    "percent":          "NUMERIC(8,4)",
    "date":             "DATE",
    "datetime":         "TIMESTAMP WITH TIME ZONE",
    "time":             "TIME",
    "phone":            "VARCHAR(40)",
    "email":            "VARCHAR(255)",
    "url":              "VARCHAR(1024)",
    "picklist":         "VARCHAR(255)",
    "multipicklist":    "TEXT",
    "reference":        "VARCHAR(18)",
    "base64":           "TEXT",
    "encryptedstring":  "TEXT",
    "anytype":          "TEXT",
    "combobox":         "VARCHAR(255)",
    "datacategorygroupreference": "VARCHAR(255)",
    "complexvalue":     "TEXT",
    "address":          "TEXT",
    "location":         "TEXT",
}

STANDARD_AUDIT_COLS = """\
    last_synced        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_status        VARCHAR(50)              DEFAULT 'pending'"""

SKIP_FIELDS = {"Id"}  # Already mapped to salesforce_id


def sf_type_to_pg(sf_type: str, length: int = 0) -> str:
    pg_type = SF_TYPE_MAP.get(sf_type.lower(), "TEXT")
    # Override VARCHAR length from field metadata if available
    if pg_type == "VARCHAR(255)" and length and 0 < length < 1024:
        pg_type = f"VARCHAR({length})"
    return pg_type


def col_name(sf_field_name: str) -> str:
    """Convert Salesforce field name to a PostgreSQL column name."""
    name = sf_field_name.lower()
    if name.endswith("__c"):
        name = name[:-3]  # strip __c
    return name


def generate_table_sql(describe: dict) -> str:
    obj_name = describe["name"]
    table = obj_name.lower().replace("__c", "")
    label = describe.get("label", obj_name)

    fields = describe.get("fields", [])

    lines = [f"-- ── {label} ({obj_name}) ─────────────────────────────────"]
    lines.append(f"CREATE TABLE IF NOT EXISTS {table} (")
    lines.append(f"    id              BIGSERIAL PRIMARY KEY,")
    lines.append(f"    salesforce_id   VARCHAR(18) NOT NULL UNIQUE,")

    index_cols = ["salesforce_id"]

    for field in fields:
        sf_name = field["name"]
        if sf_name in SKIP_FIELDS:
            continue
        if not field.get("createable", True) and not field.get("updateable", True):
            continue  # skip system-only fields we can't write back

        pg_col = col_name(sf_name)
        sf_type = field.get("type", "string")
        length = field.get("length", 0)
        pg_type = sf_type_to_pg(sf_type, length)

        nullable = "" if field.get("nillable", True) else " NOT NULL"
        comment = f"  -- SF: {sf_name} ({sf_type})" if sf_name != pg_col.upper() else ""
        lines.append(f"    {pg_col:<30} {pg_type}{nullable},{comment}")

        # Track reference fields for indexing
        if sf_type == "reference":
            index_cols.append(pg_col)

    lines.append(f"    {STANDARD_AUDIT_COLS}")
    lines.append(");")
    lines.append("")

    # Indexes
    lines.append(f"CREATE UNIQUE INDEX IF NOT EXISTS idx_{table}_sf_id ON {table}(salesforce_id);")
    lines.append(f"CREATE INDEX        IF NOT EXISTS idx_{table}_sync  ON {table}(sync_status, last_synced);")
    for col in index_cols[1:]:  # skip salesforce_id (already unique indexed)
        lines.append(f"CREATE INDEX        IF NOT EXISTS idx_{table}_{col} ON {table}({col});")
    lines.append("")

    return "\n".join(lines)


def main():
    metadata_files = sorted(glob.glob(str(METADATA_DIR / "*.json")))

    if not metadata_files:
        print(f"No metadata JSON files found in {METADATA_DIR}")
        print("Run: sf sobject describe --sobject <ObjectName> --json > "
              f"{METADATA_DIR}/<ObjectName>.json")
        return

    blocks = [
        "-- ============================================================",
        "-- Custom Object Tables (auto-generated by scripts/generate_schema.py)",
        "-- Do not edit manually — re-run the script to regenerate.",
        "-- ============================================================",
        "",
    ]

    for path in metadata_files:
        with open(path) as f:
            data = json.load(f)

        # sf sobject describe --json wraps the result in {"status":0,"result":{...}}
        describe = data.get("result", data)
        obj_name = describe.get("name", "")

        if not obj_name:
            print(f"  Skipping {path} — no 'name' field found")
            continue

        print(f"  Generating table for: {obj_name}")
        blocks.append(generate_table_sql(describe))

    OUTPUT_FILE.write_text("\n".join(blocks))
    print(f"\nSchema written to: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
